name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: PACKAGE=all make github-action

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Build"
          description: "To run this program, you'll need the QEMU emulator. You can install it on most Linux distributions using your package manager. Once QEMU is installed, you can run the program using the following command: ```qemu-system-x86_64 -drive file=boot-kot.img -machine q35 -m 2G -smp cores=4 -serial stdio -device e1000e,netdev=net0 -netdev user,id=net0,hostfwd=tcp::5000-:5000,hostfwd=udp::5000-:5000```"
          files: |
            target/liamd/boot-kot.img
            target/liamd/boot-kot.vdi
            target/liamd/boot-kot.vmdk
